export { organizationRestController } from './organization';
export { custManagerRestController } from './custManager';
export { sysParamRestController } from './sysParam'
export { sysRegionRestController } from './sysRegion'
export { consumerDetailsRestController } from './consumerDetails';
export { chartRestController } from './chart';
export { extraRestController } from './extra';
export { globalParamRestController } from './globalParam';
export { estimateRestController } from './estimate';
export { noticeTemplateRestController } from './noticeTemplate';
export { sysNoticeRestController } from './sysNotice';
export { manageNoticeRestController } from './manageNotice';
export { ordersRestController } from './orders';
export { syslogRestController } from './operateDaily';
export { advertRestController } from './advert';
export { fileRestController } from './file';
export { regionNoticeRestController } from './regionNotice';
export { noticeFailRecordRestController } from './noticeFailRecord';//新增发送失败列表服务
export { managerTeamRestController } from './managerTeam';
export { questionDetailsRestController } from './questionDetails';
export { knowledgeRestController } from './knowledge';
export { knowledgeTypeRestController } from './knowledgeType';
export { calendarFestivalRestController } from './calendarFestival';
export { buttonRestController } from './button';
export { dataAuthorityRestController } from './dataAuthority';